apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-viz-cert-tsl
  namespace: linkerd-viz
spec:
  secretName: linkerd-viz-cert-tsl
  dnsNames:    
    - ${host}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  duration: 2160h0m0s
  renewBefore: 360h0m0s