apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert-tsl
  namespace: monitoring
spec:
  secretName: prometheus-cert-tsl
  dnsNames:    
    - ${host}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  duration: 2160h0m0s
  renewBefore: 360h0m0s