apiVersion: v1
kind: Service
metadata:
  name: api-security
  namespace: {{ include "asset-chart.namespace" . }}
spec:
  selector:
    app: api-security
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort