apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: {{ include "asset-chart.namespace" . }}
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server

  template:
    metadata:
      labels:
        app: eureka-server
      annotations:
        linkerd.io/inject: enabled        
    spec:
      nodeSelector:
        app: api-apps    
      containers:
        - name: eureka-server
#          image: samuelest/eureka-server:latest
          image: {{.Values.asset.eureka.image }}
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: azure
          resources:
            requests:
              memory: {{.Values.asset.eureka.memory }}
      # nodeSelector:
      #   app: api-apps

   