apiVersion: v1
kind: Service
metadata:
  name: api-notifications
  namespace: {{ include "asset-chart.namespace" . }}
spec:
  selector:
    app: api-notifications
  ports:
    - port: 8088
  type: NodePort