apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    chart: prometheus-operator-9.3.2
    release: prometheus-operator
  name: prometheus-operator-cstor-alertmanager.rules
  namespace: default
spec:
  groups:
    - name: cstoralertmanager.rules
      rules:
        - alert: CStorVolumeUsageCritical
          annotations:
            message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim
              }} in Namespace {{ $labels.namespace }} is only {{ printf "%0.2f" $value
              }}% free.
          expr: |
            100 * kubelet_volume_stats_available_bytes{job="kubelet"}
              /
            kubelet_volume_stats_capacity_bytes{job="kubelet"}
              < 10
          for: 1m
          labels:
            severity: critical
