# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt
#   # namespace: cert-manager
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: dev@asset.tech
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: letsencrypt
#     solvers:
#       - http01:
#           ingress:
#             class: nginx


apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt  
spec:
  acme:    
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fanxwsam@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azureDNS:
          clientID: ${clientID}
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: ${subscriptionID}
          tenantID: ${tenantID}
          resourceGroupName: ${resourceGroupName}
          hostedZoneName: ${hostedZoneName}
          environment: AzurePublicCloud