apiVersion: v1
kind: Secret
metadata:
  name: cosmos-db-secret
  namespace: {{ include "asset-chart.namespace" . }}
type: Opaque
data:
  database: {{.Values.asset.users.dataSource.database }}
  key: {{.Values.asset.users.dataSource.key }}
  uri: {{.Values.asset.users.dataSource.uri }}