apiVersion: v1
kind: Service
metadata:
  name: apigw-service
  namespace: {{ include "asset-chart.namespace" . }}
  labels:
    app: apigw
spec:
  type: ClusterIP
  selector:
    app: apigw
  ports:
    - port: 8083
      targetPort: 8083
