apiVersion: v1
kind: Service
metadata:
  name: api-fraud
  namespace: {{ include "asset-chart.namespace" . }}
spec:
  selector:
    app: api-fraud
  ports:
    - port: 80
      targetPort: 8081
  type: NodePort